/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package secretariafinal;

import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import secretariafinal.IngresarDocentes;
import secretariafinal.metodos;

/**
 *
 * @author NATANAEL MORENO
 */
public class EditarDocente extends javax.swing.JFrame {

    /**
     * Creates new form EditarDocente
     */
    ResultSet rs = null;
    int cantidad, mayor;
    private int nombre = 150;
    metodos llenar = new metodos();
    boolean encontrado = false;

    metodos elim = new metodos();

    public EditarDocente() {
        initComponents();
        bloquear();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        rbgeneral = new javax.swing.JRadioButton();
        rbasesor = new javax.swing.JRadioButton();
        txtcodigo = new javax.swing.JTextField();
        txtnombre = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btneditar = new javax.swing.JButton();
        btnguardar = new javax.swing.JButton();
        btneliminar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        buttonGroup1.add(rbgeneral);
        rbgeneral.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        rbgeneral.setText("General");
        rbgeneral.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbgeneralActionPerformed(evt);
            }
        });
        getContentPane().add(rbgeneral, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 60, -1, -1));

        buttonGroup1.add(rbasesor);
        rbasesor.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        rbasesor.setText("Asesor");
        rbasesor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbasesorActionPerformed(evt);
            }
        });
        getContentPane().add(rbasesor, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 60, -1, -1));
        getContentPane().add(txtcodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, 263, -1));

        txtnombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtnombreKeyTyped(evt);
            }
        });
        getContentPane().add(txtnombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 200, 470, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(240, 240, 240));
        jLabel1.setText("Id");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(240, 240, 240));
        jLabel2.setText("Nombre");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, -1, -1));

        btneditar.setBackground(new java.awt.Color(102, 102, 102));
        btneditar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btneditar.setText("Buscar");
        btneditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneditarActionPerformed(evt);
            }
        });
        getContentPane().add(btneditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 110, 90, 40));

        btnguardar.setBackground(new java.awt.Color(102, 102, 102));
        btnguardar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnguardar.setText("Guardar Edicion");
        btnguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnguardarActionPerformed(evt);
            }
        });
        getContentPane().add(btnguardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 190, 150, 40));

        btneliminar.setBackground(new java.awt.Color(102, 102, 102));
        btneliminar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btneliminar.setText("Eliminar");
        btneliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneliminarActionPerformed(evt);
            }
        });
        getContentPane().add(btneliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 260, 110, 40));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(240, 240, 240));
        jLabel3.setText("Seleccione la opcion que desea editar ");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 350, 23));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/red-backgrounds-wallpaper-1280x1024.jpg"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 850, 400));

        jButton1.setText("Regresar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(617, 367, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btneditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneditarActionPerformed
        String cod = JOptionPane.showInputDialog("Ingrese el codigo");
        if (rbasesor.isSelected()) {
            rs = llenar.buscarasesor(cod);

            encontrado = false;
            try {
                while (rs.next()) {
                    this.txtcodigo.setText(rs.getString(1));
                    this.txtnombre.setText(rs.getString(2));
                    encontrado = true;

                }
                if (encontrado == false) {
                    JOptionPane.showMessageDialog(rootPane, "Registro no encontrado!!!", "AVISO DEL SISTEMA", 0);
                    //this.txtCodigo.setText("");
                }
            } catch (SQLException ex) {
                System.out.println(ex.getMessage());
                JOptionPane.showMessageDialog(rootPane, ex.getMessage(), "AVISO DEL SISTEMA", 0);
            }
            desbloquearR();
        } else {

            rs = llenar.buscargeneral(cod);

            encontrado = false;
            try {
                while (rs.next()) {
                    this.txtcodigo.setText(rs.getString(1));
                    this.txtnombre.setText(rs.getString(2));
                    encontrado = true;

                }
                if (encontrado == false) {
                    JOptionPane.showMessageDialog(rootPane, "Registro no encontrado!!!", "AVISO DEL SISTEMA", 0);
                    //this.txtCodigo.setText("");
                }
            } catch (SQLException ex) {
                System.out.println(ex.getMessage());
                JOptionPane.showMessageDialog(rootPane, ex.getMessage(), "AVISO DEL SISTEMA", 0);
            }
            desbloquearR();

        }
        desbloquearg();
    }//GEN-LAST:event_btneditarActionPerformed

    private void rbgeneralActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbgeneralActionPerformed
        desbloquear();
        limpiar();
    }//GEN-LAST:event_rbgeneralActionPerformed

    private void rbasesorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbasesorActionPerformed
        desbloquear();
        limpiar();
    }//GEN-LAST:event_rbasesorActionPerformed

    private void btnguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnguardarActionPerformed
        if (rbasesor.isSelected()) {
            llenar.modificarasesor(Integer.parseInt(this.txtcodigo.getText()), this.txtnombre.getText());
            JOptionPane.showMessageDialog(null, "Ingreso exitoso");
        } else {
            llenar.modificargeneral(Integer.parseInt(this.txtcodigo.getText()), this.txtnombre.getText());
            JOptionPane.showMessageDialog(null, "Ingreso exitoso");
        }
        bloquearg();
        limpiar();
        bloquearN();
    }//GEN-LAST:event_btnguardarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        IngresarDocentes regresar = new IngresarDocentes();
        regresar.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btneliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneliminarActionPerformed

        String cod = txtcodigo.getText();

        if (rbasesor.isSelected()) {
            elim.eliminarasesor(cod);
            JOptionPane.showMessageDialog(null, "Eliminacion exitosa");
        } else {
            elim.eliminargeneral(cod);
            JOptionPane.showMessageDialog(null, "Eliminacion exitosa");
        }
        limpiar();
    }//GEN-LAST:event_btneliminarActionPerformed

    private void txtnombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnombreKeyTyped
        if (txtnombre.getText().length() == nombre) {
            evt.consume();
        }
    }//GEN-LAST:event_txtnombreKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditarDocente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditarDocente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditarDocente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditarDocente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditarDocente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btneditar;
    private javax.swing.JButton btneliminar;
    private javax.swing.JButton btnguardar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JRadioButton rbasesor;
    private javax.swing.JRadioButton rbgeneral;
    private javax.swing.JTextField txtcodigo;
    private javax.swing.JTextField txtnombre;
    // End of variables declaration//GEN-END:variables
public void desbloquearR() {
        txtnombre.setEnabled(true);
    }

    public void desbloquearg() {
        btnguardar.setEnabled(true);
    }

    public void bloquearg() {
        btnguardar.setEnabled(false);
    }

    public void bloquearN() {
        txtnombre.setEnabled(false);
    }

    public void bloquear() {

        txtcodigo.setEnabled(false);
        txtnombre.setEnabled(false);
        btneditar.setEnabled(false);
        btnguardar.setEnabled(false);
        btneliminar.setEnabled(false);
    }

    public void desbloquear() {

        txtcodigo.setEnabled(false);
        txtnombre.setEnabled(false);
        btneditar.setEnabled(true);
        btneliminar.setEnabled(true);
        ;
    }

    public void limpiar() {
        txtcodigo.setText("");
        txtnombre.setText("");
    }
}
