/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package secretariafinal;

import secretariafinal.generarInforme;
import secretariafinal.menu;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import secretariafinal.metodos;

/**
 *
 * @author NATANAEL MORENO
 */
public class principal extends javax.swing.JFrame {

    ResultSet rs = null;
    metodos metod = new metodos();
    DefaultComboBoxModel modeloDirector = new DefaultComboBoxModel();
    DefaultComboBoxModel modeloAsesor = new DefaultComboBoxModel();
    DefaultComboBoxModel modelocarrera = new DefaultComboBoxModel();
    int numero;
    private int ciclo = 1, anio = 4, nombre = 150, carnet = 7, direccion = 100, telefono = 8;
    private int tema = 500, fecha=9, uv=3;
    metodos director = new metodos();
    metodos asesor = new metodos();
    metodos carrera = new metodos();
    metodos llamar = new metodos();
    int cantidad, mayor;

    public principal() {
        initComponents();
        bloquear();
          this.setLocationRelativeTo(rootPane);

         setTitle(" Departamento de Economia");
        txtcodigo.setEditable(false);
        rs = carrera.llenarCarrera();
        modelocarrera.addElement("Seleccione");
        try {
            while (rs.next()) {
                modelocarrera.addElement(rs.getString(1));
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, ex.getMessage(), "Error", 0);
        }
        cmbcarrera.setModel(modelocarrera);

        // llenado de combobox articulos
        rs = director.llenarDirector();
        modeloDirector.addElement("Seleccione");
        try {
            while (rs.next()) {
                modeloDirector.addElement(rs.getString(1));
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, ex.getMessage(), "Error", 0);
        }
        cmbdirector.setModel(modeloDirector);

        // llenado de combobox materiales
        rs = asesor.llenarAsesor();
        modeloAsesor.addElement("Seleccione");
        try {
            while (rs.next()) {
                modeloAsesor.addElement(rs.getString(1));
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, ex.getMessage(), "Error", 0);
        }
        cmbasesor.setModel(modeloAsesor);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtciclo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtaniaca = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtnombre = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtcarnet = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtdireccion = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtcodigocarrera = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtlugar = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtplan = new javax.swing.JTextField();
        txtcodigo = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txtingreso = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txtegreso = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txttema = new javax.swing.JTextArea();
        jLabel19 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        txtuv = new javax.swing.JTextField();
        cmbdirector = new javax.swing.JComboBox<>();
        jLabel23 = new javax.swing.JLabel();
        cmbasesor = new javax.swing.JComboBox<>();
        cmbcarrera = new javax.swing.JComboBox<>();
        btnregresar = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        btnnuevo = new javax.swing.JButton();
        txtfinal = new javax.swing.JFormattedTextField();
        txtinicio = new javax.swing.JFormattedTextField();
        jLabel18 = new javax.swing.JLabel();
        txtteltra = new javax.swing.JTextField();
        txttelefono = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 0, 420, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(240, 240, 240));
        jLabel2.setText("Ciclo");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 80, -1, -1));

        txtciclo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtcicloKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtcicloKeyTyped(evt);
            }
        });
        getContentPane().add(txtciclo, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 80, 80, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(240, 240, 240));
        jLabel3.setText("Año academico");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 80, -1, -1));

        txtaniaca.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtaniacaKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtaniacaKeyTyped(evt);
            }
        });
        getContentPane().add(txtaniaca, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 80, 100, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(240, 240, 240));
        jLabel4.setText("Nombre del Egresado");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 150, -1, -1));

        txtnombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtnombreKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtnombreKeyTyped(evt);
            }
        });
        getContentPane().add(txtnombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 150, 450, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(240, 240, 240));
        jLabel5.setText("Carnet");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 270, -1, -1));

        txtcarnet.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtcarnetKeyTyped(evt);
            }
        });
        getContentPane().add(txtcarnet, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 270, 140, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(240, 240, 240));
        jLabel6.setText("Direccion de residencia");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 190, -1, -1));

        txtdireccion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtdireccionKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtdireccionKeyTyped(evt);
            }
        });
        getContentPane().add(txtdireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 190, 450, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(240, 240, 240));
        jLabel7.setText("Telefono");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 270, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(240, 240, 240));
        jLabel8.setText("Carrera");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 230, 70, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(240, 240, 240));
        jLabel9.setText("Codigo");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 230, -1, -1));
        getContentPane().add(txtcodigocarrera, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 230, 90, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(240, 240, 240));
        jLabel10.setText("Lugar de trabajo");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 310, -1, -1));

        txtlugar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtlugarKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtlugarKeyTyped(evt);
            }
        });
        getContentPane().add(txtlugar, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 310, 410, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(240, 240, 240));
        jLabel12.setText("Telefono de trabajo");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 310, -1, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(240, 240, 240));
        jLabel13.setText("Plan de estudios");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 230, -1, -1));
        getContentPane().add(txtplan, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 230, 90, -1));

        txtcodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcodigoActionPerformed(evt);
            }
        });
        getContentPane().add(txtcodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 40, 90, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(240, 240, 240));
        jLabel11.setText("Director general");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 360, -1, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(240, 240, 240));
        jLabel14.setText("Fecha de Inicio");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 500, -1, -1));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(240, 240, 240));
        jLabel15.setText("Año de Ingreso:");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 450, -1, -1));

        txtingreso.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtingresoKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtingresoKeyTyped(evt);
            }
        });
        getContentPane().add(txtingreso, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 450, 220, -1));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(240, 240, 240));
        jLabel16.setText("Año de Egreso:");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 450, 140, -1));

        txtegreso.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtegresoKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtegresoKeyTyped(evt);
            }
        });
        getContentPane().add(txtegreso, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 450, 100, -1));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(240, 240, 240));
        jLabel17.setText("Fecha de fin");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 500, -1, 20));

        txttema.setColumns(20);
        txttema.setRows(5);
        txttema.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txttemaKeyTyped(evt);
            }
        });
        jScrollPane1.setViewportView(txttema);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 580, 920, 110));
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 720, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(240, 240, 240));
        jLabel1.setText("Inscripcion de Proceso de Grado");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 20, 410, 40));

        jButton1.setBackground(new java.awt.Color(102, 102, 102));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(240, 240, 240));
        jButton1.setText("Guardar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 590, 100, -1));

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(240, 240, 240));
        jLabel22.setText("Total de u.v.");
        getContentPane().add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 270, -1, -1));

        txtuv.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtuvKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtuvKeyTyped(evt);
            }
        });
        getContentPane().add(txtuv, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 270, 90, -1));

        getContentPane().add(cmbdirector, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 360, 630, -1));

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(240, 240, 240));
        jLabel23.setText("Docente Asesor");
        getContentPane().add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 400, -1, -1));

        getContentPane().add(cmbasesor, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 400, 630, -1));

        cmbcarrera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbcarreraActionPerformed(evt);
            }
        });
        getContentPane().add(cmbcarrera, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 230, 450, -1));

        btnregresar.setBackground(new java.awt.Color(102, 102, 102));
        btnregresar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnregresar.setForeground(new java.awt.Color(240, 240, 240));
        btnregresar.setText("Regresar");
        btnregresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnregresarActionPerformed(evt);
            }
        });
        getContentPane().add(btnregresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 630, 100, -1));

        jButton3.setBackground(new java.awt.Color(102, 102, 102));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(240, 240, 240));
        jButton3.setText("Mostrar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 550, 100, -1));

        btnnuevo.setBackground(new java.awt.Color(102, 102, 102));
        btnnuevo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnnuevo.setForeground(new java.awt.Color(240, 240, 240));
        btnnuevo.setText("Nuevo");
        btnnuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnuevoActionPerformed(evt);
            }
        });
        getContentPane().add(btnnuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 90, 100, 50));

        try {
            txtfinal.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####-##-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtfinal.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtfinal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtfinalKeyTyped(evt);
            }
        });
        getContentPane().add(txtfinal, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 500, 250, 30));

        try {
            txtinicio.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####-##-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtinicio.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtinicio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtinicioKeyTyped(evt);
            }
        });
        getContentPane().add(txtinicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 500, 240, 30));

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(240, 240, 240));
        jLabel18.setText("Tema :");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 550, -1, -1));

        txtteltra.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtteltra.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtteltraKeyTyped(evt);
            }
        });
        getContentPane().add(txtteltra, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 310, 140, -1));

        txttelefono.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txttelefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txttelefonoKeyTyped(evt);
            }
        });
        getContentPane().add(txttelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 270, 130, -1));

        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/red-backgrounds-wallpaper-1280x1024.jpg"))); // NOI18N
        getContentPane().add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1290, 770));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (this.txtnombre.getText() == null) {
            JOptionPane.showMessageDialog(rootPane, "Debe seleccionar un nombre", "AVISO DEL SISTEMA", 1);

        } else if (this.txtcarnet.getText() == null) {
            JOptionPane.showMessageDialog(rootPane, "Debe seleccionar un carnet", "AVISO DEL SISTEMA", 2);

        } else if (this.txtdireccion.getText() == null) {
            JOptionPane.showMessageDialog(rootPane, "Debe seleccionar una dirreccion de domicilio", "AVISO DEL SISTEMA", 2);

        } else if (this.txttelefono.getText() == null) {
            JOptionPane.showMessageDialog(rootPane, "Debe seleccionar un  telefono", "AVISO DEL SISTEMA", 2);

        } else {

            llamar.insertarAlumno(this.txtcarnet.getText(), this.txtnombre.getText(), this.txtdireccion.getText(), Integer.parseInt(this.txttelefono.getText()), this.txtlugar.getText(), Integer.parseInt(this.txtteltra.getText()));
            // llamar.insertarCarrera(this.txtcodigocarrera.getText(),this.cmbcarrera.getSelectedIndex(),Integer.parseInt(this.txtplan.getText()));
            llamar.insertarInscripcion(Integer.parseInt(this.txtcodigo.getText()), Integer.parseInt(this.txtaniaca.getText()), Integer.parseInt(this.txtciclo.getText()), this.txtuv.getText(), Integer.parseInt(this.txtingreso.getText()), Integer.parseInt(this.txtegreso.getText()), this.txtnombre.getText(), String.valueOf(this.cmbasesor.getSelectedItem()), this.txtcodigocarrera.getText(), this.txttema.getText(), this.txtinicio.getText(), this.txtfinal.getText(), this.cmbasesor.getSelectedIndex(), this.cmbdirector.getSelectedIndex(), this.txtcarnet.getText());
            JOptionPane.showMessageDialog(null, "ingreso exitoso");

        }

        limpiar();
        bloquear();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtcodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcodigoActionPerformed

    private void cmbcarreraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbcarreraActionPerformed
        String car;
        car = String.valueOf(cmbcarrera.getSelectedItem());
        rs = metod.traercodigo(car);
        try {
            while (rs.next()) {

                txtcodigocarrera.setText(rs.getString(1));

            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, ex.getMessage(), "Error", 0);

        }
        rs = metod.traerplan(car);
        try {
            while (rs.next()) {

                txtplan.setText(rs.getString(1));

            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, ex.getMessage(), "Error", 0);

        }
    }//GEN-LAST:event_cmbcarreraActionPerformed

    private void btnregresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnregresarActionPerformed
        menu regresar = new menu();
        regresar.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnregresarActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        generarInforme ropa = new generarInforme();
        ropa.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void txtcicloKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcicloKeyPressed
        char c = evt.getKeyChar();
        int car = evt.getKeyChar();
        if (Character.isLetter(c) || (car >= 32 && car <= 47)) {
            JOptionPane.showMessageDialog(null, "solo introduzca numeros");
            txtciclo.setText(null);
        }
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            numero = Integer.parseInt(txtciclo.getText());
            if (numero < 0) {
                JOptionPane.showMessageDialog(null, "debe estar ser mayor o igual a cero");
                txtciclo.setText("");
            } else {
                txtaniaca.requestFocus();
            }
        }
    }//GEN-LAST:event_txtcicloKeyPressed

    private void btnnuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnuevoActionPerformed
        // TODO add your handling code here:rs = null;
        desbloquear();
        rs = llamar.contarRegistros5();
        try {
            while (rs.next()) {
                cantidad = rs.getInt(1);
                if (cantidad != 0) {
                    rs = null;
                    //método en clase Clientes
                    rs = llamar.mayorRegistro5();
                    while (rs.next()) {
                        mayor = rs.getInt(1) + 1;
                        //recuerde que debe completar 5 digitos
                        if (mayor < 10) {
                            txtcodigo.setText("0" + mayor);
                        } else if (mayor < 100) {
                            this.txtcodigo.setText("00" + mayor);
                        } else if (mayor < 1000) {
                            txtcodigo.setText("0" + mayor);
                        } else {
                            txtcodigo.setText("" + mayor);
                        }
                    }
                    txtnombre.requestFocus();
                } else {
                    txtcodigo.setText("0" + 1);
                    txtnombre.requestFocus();
                }
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, ex.getMessage(), "AVISO DEL SISTEMA", 0);
        }
    }//GEN-LAST:event_btnnuevoActionPerformed

    private void txtaniacaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtaniacaKeyPressed
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        int car = evt.getKeyChar();
        if (Character.isLetter(c) || (car >= 32 && car <= 47)) {
            JOptionPane.showMessageDialog(null, "solo introduzca numeros");
            txtaniaca.setText(null);
        }
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            numero = Integer.parseInt(txtaniaca.getText());
            if (numero < 0) {
                JOptionPane.showMessageDialog(null, "debe estar ser mayor o igual a cero");
                txtaniaca.setText("");
            } else {
                txtnombre.requestFocus();
            }
        }
    }//GEN-LAST:event_txtaniacaKeyPressed

    private void txtegresoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtegresoKeyPressed
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        int car = evt.getKeyChar();
        if (Character.isLetter(c) || (car >= 32 && car <= 47)) {
            JOptionPane.showMessageDialog(null, "solo introduzca numeros");
            txtegreso.setText(null);
        }
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            numero = Integer.parseInt(txtegreso.getText());
            if (numero < 0) {
                JOptionPane.showMessageDialog(null, "debe estar ser mayor o igual a cero");
                txtegreso.setText("");
            } else {

            }
        }
    }//GEN-LAST:event_txtegresoKeyPressed

    private void txtuvKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtuvKeyPressed
        char c = evt.getKeyChar();
        int car = evt.getKeyChar();
        if (Character.isLetter(c) || (car >= 32 && car <= 47)) {
            JOptionPane.showMessageDialog(null, "solo introduzca numeros");
            txtuv.setText(null);
        }
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            numero = Integer.parseInt(txtuv.getText());
            if (numero < 0) {
                JOptionPane.showMessageDialog(null, "debe estar ser mayor o igual a cero");
                txtuv.setText("");
            } else {
            }
        }
    }//GEN-LAST:event_txtuvKeyPressed

    private void txtnombreKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnombreKeyPressed

        char c = evt.getKeyChar();
        int car = evt.getKeyChar();
        if (Character.isDigit(c) || (car >= 0 && car <= 9)) {
            JOptionPane.showMessageDialog(null, "solo introduzca letras");
            txtnombre.setText(null);

        }
    }//GEN-LAST:event_txtnombreKeyPressed

    private void txtdireccionKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtdireccionKeyPressed
        char c = evt.getKeyChar();
        int car = evt.getKeyChar();
        if (Character.isDigit(c) || (car >= 0 && car <= 9)) {
            JOptionPane.showMessageDialog(null, "solo introduzca letras");
            txtdireccion.setText(null);
        }
    }//GEN-LAST:event_txtdireccionKeyPressed

    private void txtlugarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtlugarKeyPressed
        char c = evt.getKeyChar();
        int car = evt.getKeyChar();
        if (Character.isDigit(c) || (car >= 0 && car <= 9)) {
            JOptionPane.showMessageDialog(null, "solo introduzca letras");
            txtlugar.setText(null);

        }
    }//GEN-LAST:event_txtlugarKeyPressed

    private void txtingresoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtingresoKeyPressed
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        int car = evt.getKeyChar();
        if (Character.isLetter(c) || (car >= 32 && car <= 47)) {
            JOptionPane.showMessageDialog(null, "solo introduzca numeros");
            txtingreso.setText(null);
        }
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            numero = Integer.parseInt(txtingreso.getText());
            if (numero < 0) {
                JOptionPane.showMessageDialog(null, "debe estar ser mayor o igual a cero");
                txtingreso.setText("");
            } else {

            }
        }
    }//GEN-LAST:event_txtingresoKeyPressed

    private void txtcicloKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcicloKeyTyped
        if (txtciclo.getText().length() == ciclo) {
            evt.consume();
        }
    }//GEN-LAST:event_txtcicloKeyTyped

    private void txtaniacaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtaniacaKeyTyped
        if (txtaniaca.getText().length() == anio) {
            evt.consume();
        }
    }//GEN-LAST:event_txtaniacaKeyTyped

    private void txtnombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnombreKeyTyped
        if (txtnombre.getText().length() == nombre) {
            evt.consume();
        }
    }//GEN-LAST:event_txtnombreKeyTyped

    private void txtdireccionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtdireccionKeyTyped
        if (txtdireccion.getText().length() == direccion) {
            evt.consume();
        }
    }//GEN-LAST:event_txtdireccionKeyTyped

    private void txtcarnetKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcarnetKeyTyped
        if (txtcarnet.getText().length() == carnet) {
            evt.consume();
        }
    }//GEN-LAST:event_txtcarnetKeyTyped

    private void txtingresoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtingresoKeyTyped
        if (txtingreso.getText().length() == anio) {
            evt.consume();
        }
    }//GEN-LAST:event_txtingresoKeyTyped

    private void txtegresoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtegresoKeyTyped
        if (txtegreso.getText().length() == anio) {
            evt.consume();
        }
    }//GEN-LAST:event_txtegresoKeyTyped

    private void txttemaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txttemaKeyTyped
        if (txttema.getText().length() == tema) {
            evt.consume();
        }
    }//GEN-LAST:event_txttemaKeyTyped

    private void txtinicioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtinicioKeyTyped
         if (txtinicio.getText().length() == fecha) {
            evt.consume();
        }
    }//GEN-LAST:event_txtinicioKeyTyped

    private void txtfinalKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtfinalKeyTyped
            if (txtfinal.getText().length() == fecha) {
            evt.consume();
        }
    }//GEN-LAST:event_txtfinalKeyTyped

    private void txtlugarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtlugarKeyTyped
            if (txtlugar.getText().length() == direccion) {
            evt.consume();
        }
    }//GEN-LAST:event_txtlugarKeyTyped

    private void txtuvKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtuvKeyTyped
              if (txtuv.getText().length() == uv) {
            evt.consume();
        }
    }//GEN-LAST:event_txtuvKeyTyped

    private void txttelefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txttelefonoKeyTyped
          if (txttelefono.getText().length() == telefono) {
            evt.consume();
        }
    }//GEN-LAST:event_txttelefonoKeyTyped

    private void txtteltraKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtteltraKeyTyped
         if (txtteltra.getText().length() == telefono) {
            evt.consume();
        }
    }//GEN-LAST:event_txtteltraKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnnuevo;
    private javax.swing.JButton btnregresar;
    private javax.swing.JComboBox<String> cmbasesor;
    private javax.swing.JComboBox<String> cmbcarrera;
    private javax.swing.JComboBox<String> cmbdirector;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtaniaca;
    private javax.swing.JTextField txtcarnet;
    private javax.swing.JTextField txtciclo;
    private javax.swing.JTextField txtcodigo;
    private javax.swing.JTextField txtcodigocarrera;
    private javax.swing.JTextField txtdireccion;
    private javax.swing.JTextField txtegreso;
    private javax.swing.JFormattedTextField txtfinal;
    private javax.swing.JTextField txtingreso;
    private javax.swing.JFormattedTextField txtinicio;
    private javax.swing.JTextField txtlugar;
    private javax.swing.JTextField txtnombre;
    private javax.swing.JTextField txtplan;
    private javax.swing.JTextField txttelefono;
    private javax.swing.JTextField txtteltra;
    private javax.swing.JTextArea txttema;
    private javax.swing.JTextField txtuv;
    // End of variables declaration//GEN-END:variables
public void bloquear() {
        txtciclo.setEnabled(false);
        txtaniaca.setEnabled(false);
        txtcarnet.setEnabled(false);
        txtcodigocarrera.setEnabled(false);
        txtdireccion.setEnabled(false);
        txtegreso.setEnabled(false);
        txtfinal.setEnabled(false);
        txtingreso.setEnabled(false);
        txtinicio.setEnabled(false);
        txtlugar.setEnabled(false);
        txtnombre.setEnabled(false);
        txtplan.setEnabled(false);
        txttelefono.setEnabled(false);
        txtteltra.setEnabled(false);
        txttema.setEnabled(false);
        txtuv.setEnabled(false);

    }

    public void desbloquear() {
        txtciclo.setEnabled(true);
        txtaniaca.setEnabled(true);
        txtcarnet.setEnabled(true);
        txtcodigocarrera.setEnabled(true);
        txtdireccion.setEnabled(true);
        txtegreso.setEnabled(true);
        txtfinal.setEnabled(true);
        txtingreso.setEnabled(true);
        txtinicio.setEnabled(true);
        txtlugar.setEnabled(true);
        txtnombre.setEnabled(true);
        txtplan.setEnabled(true);
        txttelefono.setEnabled(true);
        txtteltra.setEnabled(true);
        txttema.setEnabled(true);
        txtuv.setEnabled(true);
    }

    public void limpiar() {

        txtcodigo.setText("");
        txtciclo.setText("");
        txtaniaca.setText("");
        txtcarnet.setText("");
        txtcodigocarrera.setText("");
        txtdireccion.setText("");
        txtegreso.setText("");
        txtfinal.setText("");
        txtingreso.setText("");
        txtinicio.setText("");
        txtlugar.setText("");
        txtnombre.setText("");
        txtplan.setText("");
        txttelefono.setText("");
        txtteltra.setText("");
        txttema.setText("");
        txtuv.setText("");
        cmbcarrera.setSelectedIndex(0);
        cmbasesor.setSelectedIndex(0);
        cmbdirector.setSelectedIndex(0);
    }

}
